# Generate RSA key pair for JWT signing
resource "random_password" "jwt_private_key_passphrase" {
  length  = 32
  special = true
}

# Secrets Manager secret for JWT signing keys
resource "aws_secretsmanager_secret" "jwt_keys" {
  name                    = "${var.project_name}-${var.environment}-jwt-keys-${random_id.secret_suffix.hex}"
  description             = "RSA key pair for JWT signing"
  recovery_window_in_days = 7

  tags = {
    Name = "${var.project_name}-${var.environment}-jwt-keys"
  }
}

resource "random_id" "secret_suffix" {
  byte_length = 4
}

# Store initial placeholder - keys will be generated by Lambda on first run
resource "aws_secretsmanager_secret_version" "jwt_keys" {
  secret_id = aws_secretsmanager_secret.jwt_keys.id
  secret_string = jsonencode({
    private_key = ""
    public_key  = ""
    kid         = "default-key-1"
    alg         = "RS256"
  })

  lifecycle {
    ignore_changes = [secret_string]
  }
}
