# SSM Parameter (encrypted) for JWT signing keys
# Using SecureString type for encryption at rest
resource "aws_ssm_parameter" "jwt_keys" {
  name        = "${local.project_name}-${local.environment}-jwt-keys"
  description = "RSA key pair for JWT signing (encrypted)"
  type        = "SecureString"

  # Store initial placeholder - keys will be generated by Lambda on first run
  value = jsonencode({
    private_key = ""
    public_key  = ""
    kid         = "default-key-1"
    alg         = "RS256"
  })

  lifecycle {
    ignore_changes = [value]
  }

  tags = {
    Name = "${local.project_name}-${local.environment}-jwt-keys"
  }
}
