# SSM Parameter to store the OIDC issuer URL
# This breaks the circular dependency between Lambda and API Gateway
# The parameter is initially set with the user-provided issuer_url or a placeholder
# After deployment, it will be updated with the actual API Gateway URL if needed
resource "aws_ssm_parameter" "issuer_url" {
  name        = local.issuer_url_parameter
  description = "OIDC Issuer URL for the provider"
  type        = "String"
  overwrite   = true
  value       = local.issuer_url

  tags = {
    Name = "${local.project_name}-${local.environment}-issuer-url"
  }
}

# SSM Parameter (encrypted) for JWT signing keys
# Using SecureString type for encryption at rest with AWS managed KMS key
# Note: For enhanced security and audit capabilities, consider using a 
# customer-managed KMS key by adding: key_id = aws_kms_key.example.id
resource "aws_ssm_parameter" "jwt_keys" {
  name        = "${local.project_name}-${local.environment}-jwt-keys"
  description = "RSA key pair for JWT signing (encrypted)"
  type        = "SecureString"

  # Store initial placeholder - keys will be generated by Lambda on first run
  value = jsonencode({
    private_key = ""
    public_key  = ""
    kid         = "default-key-1"
    alg         = "RS256"
  })

  lifecycle {
    ignore_changes = [value]
  }

  tags = {
    Name = "${local.project_name}-${local.environment}-jwt-keys"
  }
}
