AWSTemplateFormatVersion: '2010-09-09'
Description: 'GitHub Actions IAM Role - Template for deploying repository-specific GitHub Actions roles that assume the shared OIDC provider'

# Stack Name: github-role-for-terraform-core-oidc

# DEPLOYMENT INSTRUCTIONS:
# PREREQUISITE: The GitHub OIDC provider must be deployed first using the github-identity-provider.yaml template.
#               This creates the shared OIDC provider that this role will reference.
#               Deploy it with stack name 'github-identity-provider' (or update OIDCProviderStackName parameter below).
# 
# 1. Copy this template to your target repository
# 2. Update the RepositoryName parameter default to match your repository name
# 3. Optionally adjust Environment parameter if needed
# 4. This template includes a comprehensive inline policy (TerraformDeploymentPolicy) with all permissions
#    required for Terraform to manage the OIDC provider infrastructure. See cloudformation/TERRAFORM_PERMISSIONS.md
#    for detailed documentation of all included permissions.
# 5. Deploy with: aws cloudformation create-stack --stack-name github-role-for-<repo-name> --template-body file://github-iam-role.yaml --capabilities CAPABILITY_NAMED_IAM

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Repository Configuration
        Parameters:
          - Organization
          - ProjectName
          - Environment
      - Label:
          default: Infrastructure References
        Parameters:
          - OIDCProviderStackName
          - TerraformAccessPolicyAccountID
    ParameterLabels:
      Organization:
        default: GitHub Organization
      ProjectName:
        default: Repository Name
      Environment:
        default: Environment
      OIDCProviderStackName:
        default: OIDC Provider Stack Name
      TerraformAccessPolicyAccountID:
        default: Terraform Access Policy Account ID

Parameters:
  Organization:
    Type: String
    Description: GitHub organization name
    Default: faccomichele
    MinLength: 1
    MaxLength: 63
    AllowedPattern: ^[a-z0-9-]+$
    ConstraintDescription: Must be lowercase alphanumeric with hyphens only
  
  ProjectName:
    Type: String
    Description: Name of the GitHub repository (change this when copying to another repo)
    Default: terraform-core-oidc
    MinLength: 1
    MaxLength: 100
    AllowedPattern: ^[a-zA-Z0-9._-]+$
    ConstraintDescription: Must be a valid GitHub repository name
  
  Environment:
    Type: String
    Description: Environment/Workspace (dev, stg, prod)
    AllowedValues:
      - dev
      - stg
      - prod
    Default: dev
  
  OIDCProviderStackName:
    Type: String
    Description: Name of the stack that deployed the GitHub OIDC provider
    Default: github-identity-provider
  
  TerraformAccessPolicyAccountID:
    Type: String
    Description: The account ID for Terraform access managed policy (from terraform-core-aws stack)

Resources:
  # IAM role for API Gateway to push logs to CloudWatch
  APIGatewayCloudWatchLogsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: API Gateway CloudWatch Logs Integration

  # IAM role for GitHub Actions (repository-specific)
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      # Role name will be auto-generated by CloudFormation with stack name prefix
      # This ensures uniqueness and follows AWS naming best practices
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub 
                - 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
                - {}
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub 'repo:${Organization}/${ProjectName}:*'
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
      ManagedPolicyArns:
        # REQUIRED: SSM parameter read policy to retrieve Terraform backend configuration
        - !Sub 'arn:aws:iam::${TerraformAccessPolicyAccountID}:policy/terraform-core-aws-tf-access-dev'
      # Inline policy with required Terraform permissions
      Policies:
        - PolicyName: TerraformDeploymentPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Lambda permissions
              - Sid: LambdaManagement
                Effect: Allow
                Action:
                  - lambda:CreateFunction
                  - lambda:DeleteFunction
                  - lambda:GetFunction
                  - lambda:GetFunctionConfiguration
                  - lambda:UpdateFunctionCode
                  - lambda:UpdateFunctionConfiguration
                  - lambda:ListVersionsByFunction
                  - lambda:PublishVersion
                  - lambda:TagResource
                  - lambda:UntagResource
                  - lambda:ListTags
                  - lambda:AddPermission
                  - lambda:RemovePermission
                  - lambda:GetPolicy
                Resource:
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:oidc-provider-${Environment}-*'
              
              # API Gateway permissions
              - Sid: APIGatewayManagement
                Effect: Allow
                Action:
                  - apigateway:GET
                  - apigateway:POST
                  - apigateway:PUT
                  - apigateway:PATCH
                  - apigateway:DELETE
                Resource:
                  - !Sub 'arn:aws:apigateway:${AWS::Region}::/restapis'
                  - !Sub 'arn:aws:apigateway:${AWS::Region}::/restapis/*'
                  - !Sub 'arn:aws:apigateway:${AWS::Region}::/tags/*'
              
              # API Gateway account settings (required for CloudWatch Logs integration)
              - Sid: APIGatewayAccountSettings
                Effect: Allow
                Action:
                  - apigateway:UpdateAccount
                  - apigateway:PATCH
                  - apigateway:GET
                Resource:
                  - !Sub 'arn:aws:apigateway:${AWS::Region}::/account'
              
              # DynamoDB permissions
              - Sid: DynamoDBManagement
                Effect: Allow
                Action:
                  - dynamodb:CreateTable
                  - dynamodb:DeleteTable
                  - dynamodb:DescribeTable
                  - dynamodb:DescribeContinuousBackups
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:ListTagsOfResource
                  - dynamodb:TagResource
                  - dynamodb:UntagResource
                  - dynamodb:UpdateTable
                  - dynamodb:UpdateContinuousBackups
                  - dynamodb:UpdateTimeToLive
                Resource:
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/oidc-provider-${Environment}-*'
              
              # S3 permissions
              - Sid: S3BucketManagement
                Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:DeleteBucket
                  - s3:GetBucketLocation
                  - s3:GetBucketPolicy
                  - s3:GetBucketVersioning
                  - s3:GetBucketPublicAccessBlock
                  - s3:GetEncryptionConfiguration
                  - s3:GetBucketAcl
                  - s3:GetBucketCORS
                  - s3:GetBucketLogging
                  - s3:GetBucketRequestPayment
                  - s3:GetBucketTagging
                  - s3:GetBucketWebsite
                  - s3:GetLifecycleConfiguration
                  - s3:GetReplicationConfiguration
                  - s3:GetAccelerateConfiguration
                  - s3:GetBucketObjectLockConfiguration
                  - s3:PutBucketPolicy
                  - s3:PutBucketVersioning
                  - s3:PutBucketPublicAccessBlock
                  - s3:PutEncryptionConfiguration
                  - s3:PutBucketAcl
                  - s3:PutBucketTagging
                  - s3:DeleteBucketPolicy
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::oidc-provider-${Environment}-assets-*'
              
              # Secrets Manager permissions
              - Sid: SecretsManagerManagement
                Effect: Allow
                Action:
                  - secretsmanager:CreateSecret
                  - secretsmanager:DeleteSecret
                  - secretsmanager:DescribeSecret
                  - secretsmanager:GetSecretValue
                  - secretsmanager:PutSecretValue
                  - secretsmanager:UpdateSecret
                  - secretsmanager:TagResource
                  - secretsmanager:UntagResource
                  - secretsmanager:ListSecretVersionIds
                  - secretsmanager:GetResourcePolicy
                Resource:
                  - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:oidc-provider-${Environment}-jwt-keys-*'
              
              # IAM permissions for Lambda execution role and API Gateway CloudWatch role
              - Sid: IAMRoleManagement
                Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRole
                  - iam:GetRolePolicy
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:ListRolePolicies
                  - iam:ListAttachedRolePolicies
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:TagRole
                  - iam:UntagRole
                  - iam:ListRoleTags
                  - iam:ListInstanceProfilesForRole
                  - iam:PassRole
                Resource:
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/oidc-provider-${Environment}-lambda-exec'
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/oidc-provider-${Environment}-api-gateway-cloudwatch'
              
              # IAM permissions for managed policies (read-only)
              - Sid: IAMPolicyReadAccess
                Effect: Allow
                Action:
                  - iam:GetPolicy
                  - iam:GetPolicyVersion
                  - iam:ListPolicyVersions
                Resource:
                  - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
              
              # CloudWatch Logs permissions (for Lambda)
              # Note: Scoped to Lambda log groups for management operations (create, delete, configure)
              - Sid: CloudWatchLogsManagement
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:DeleteLogGroup
                  - logs:DescribeLogGroups
                  - logs:ListTagsLogGroup
                  - logs:TagLogGroup
                  - logs:UntagLogGroup
                  - logs:PutRetentionPolicy
                  - logs:DeleteRetentionPolicy
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/oidc-provider-${Environment}-*'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/oidc-provider-${Environment}-*:*'
              
              # Additional CloudWatch Logs permissions for API Gateway
              # Separate statement with wildcard resource because API Gateway may create log groups
              # with different naming patterns than Lambda. logs:CreateLogGroup is intentionally
              # duplicated here to support both scoped Lambda operations and wildcard API Gateway needs.
              - Sid: CloudWatchLogsAPIGateway
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:DescribeLogGroups
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*'
              
              # Terraform state and resource discovery
              # Wildcard resource access is required for list/discovery operations that Terraform
              # uses to refresh state and detect drift. apigateway:GET is intentionally duplicated
              # here for discovery, while APIGatewayManagement has scoped resources for CRUD operations.
              - Sid: ResourceDiscovery
                Effect: Allow
                Action:
                  - apigateway:GET
                  - lambda:ListFunctions
                  - lambda:GetFunctionCodeSigningConfig
                  - dynamodb:ListTables
                  - s3:ListAllMyBuckets
                  - secretsmanager:ListSecrets
                  - iam:ListRoles
                Resource: '*'
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Organization
          Value: !Ref Organization
        - Key: Environment
          Value: !Ref Environment
        - Key: RepositoryURL
          Value: !Sub 'https://github.com/${Organization}/${ProjectName}'
        - Key: Automation
          Value: CloudFormation
        - Key: RepositoryPath
          Value: cloudformation
        - Key: RepositoryFile
          Value: github-iam-role.yaml
        - Key: Description
          Value: !Sub 'IAM role for GitHub Actions in ${Organization}/${ProjectName}'
        - Key: Region
          Value: !Ref 'AWS::Region'

Outputs:
  APIGatewayCloudWatchLogsRoleArn:
    Description: ARN of the IAM role for API Gateway CloudWatch Logs integration
    Value: !GetAtt APIGatewayCloudWatchLogsRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-APIGatewayCloudWatchLogsRoleArn'
  
  GitHubActionsRoleArn:
    Description: ARN of the IAM role for GitHub Actions
    Value: !GetAtt GitHubActionsRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-GitHubActionsRoleArn'

